Tests index show
wolox-training/dv-rails pull request #11
Opened 2018-11-17 00:09 UTC by MaaooVaass

## Summary
text for model book

## Card 
https://trello.com/c/z381r4Zx/21-crear-tests-para-el-modelo-de-book

2018-11-20 13:31 UTC, fedeest commented
All good. Fix conflicts are remember to merge previous PR first and then change this PR base.

2018-11-20 17:39 UTC, lmasello requested changes

2018-11-20 17:39 UTC, lmasello commented on spec/controllers/books_controller_spec.rb
> +    subject(:http_request) do
There may be many http requests. Use a more descriptive name, such as `index_request`. Also, you can do this in just one line with curly brackets (`{}`).

2018-11-20 17:39 UTC, lmasello commented on spec/controllers/books_controller_spec.rb
> +    it 'responses with the books json' do
typo. responds/returns?

2018-11-20 17:39 UTC, lmasello commented on spec/controllers/books_controller_spec.rb
> +    subject(:http_request) do
According to the previous comment. Here you can use `show_request`.

2018-11-21 18:00 UTC, lmasello approved these changes

2018-11-21 20:59 UTC, merged