Send an email
wolox-training/dv-rails pull request #13
Opened 2018-11-22 19:19 UTC by MaaooVaass

## Summary
Send an email

## Card
https://trello.com/c/ANn17kT0/11-mandar-email-al-usuario-cuando-se-crea-un-rent

2018-11-23 21:25 UTC, lmasello requested changes

2018-11-23 21:25 UTC, lmasello commented on app/controllers/rents_controller.rb
> +      RentWorker.perform_async(rent.id)
Call the worker before rendering the response.

2018-11-23 21:25 UTC, lmasello commented on app/workers/rent_worker.rb
> +class RentWorker
Use a more self-descriptive name. Something that when you read it, you can understand what it does. In this case, it should be something like 'RentNotificationWorker' or so.

2018-11-23 21:25 UTC, lmasello commented on app/views/rent_mailer/rent_notification.html.erb
> +<h1>Rent#send</h1>
This is ok but just for you to know: Usually, we use slim for the views.

2018-11-23 21:25 UTC, lmasello commented on config/environments/development.rb
> +    :user_name => Rails.application.secrets.user_name,
`user_name: Rails.application.secrets.user_name`

The same for the others.

2018-11-26 15:31 UTC, fedeest commented on config/environments/development.rb
> +  # config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
Eras commented code

2018-11-26 17:19 UTC, lmasello requested changes
Also, you have a file called 'dump.rdb'. This should not be in the repository.

2018-11-26 17:19 UTC, lmasello commented on app/workers/rent_notification_worker_worker.rb
> +class RentNotificationWorkerWorker
Careful with the end of this word

2018-11-26 17:19 UTC, lmasello commented on config/environments/development.rb
> +  config.active_record.migration_error = :page_loadÍ
Same here, be careful with the end.

2018-11-26 17:22 UTC, fedeest requested changes

2018-11-26 17:22 UTC, fedeest commented on app/controllers/rents_controller.rb
> +      RentNotificationWorkerWorker.perform_async(rent.id)
You have 'Worker' both times

2018-11-26 17:22 UTC, fedeest commented on app/workers/rent_notification_worker_worker.rb
> +class RentNotificationWorkerWorker
You have 'worker' twice

2018-11-27 13:15 UTC, fedeest approved these changes

2018-11-27 13:19 UTC, lmasello approved these changes

2018-11-27 14:15 UTC, merged