Installation and configuration of Active Admin
wolox-training/dv-rails pull request #15
Opened 2018-11-26 23:11 UTC by MaaooVaass

## Summary
Instalación y configuración de Active Admin 

## Card
https://trello.com/c/BOBOTBr0/10-instalar-y-configurar-active-admin

2018-11-27 13:17 UTC, fedeest requested changes
Minor change, rest seems fine

2018-11-27 13:17 UTC, fedeest commented on app/admin/dashboard.rb
> +    # end
Erase commented code

2018-11-27 13:30 UTC, lmasello approved these changes
Fede's corrections and it's good to go! Please, also add the screenshot of the active admin page in the description of the PR.

2018-11-27 21:42 UTC, lmasello approved these changes

2018-11-28 14:17 UTC, fedeest approved these changes

2018-11-28 14:36 UTC, merged