BookSuggestion
wolox-training/dv-rails pull request #16
Opened 2018-11-28 14:20 UTC by MaaooVaass

## Summary 
se crea el modelo de BookSuggestions para que un usuario pueda sugerir nuevos libros en la plataforma.

## Card 
https://trello.com/c/vQaWc47t/26-crear-modelo-de-booksuggestion

2018-11-28 14:24 UTC, fedeest requested changes
Also, add the .DS_Store files to the .gitignore

2018-11-28 14:24 UTC, fedeest commented on spec/factories/book_suggestions.rb
> +    user { nil }
User the Faker Gem for the factories of models. That way you can get random values.

2018-11-28 14:41 UTC, lmasello requested changes

2018-11-28 14:41 UTC, lmasello commented on app/models/book_suggestion.rb
> +  belongs_to :user
Don't forget to add the inverse relation. This is, the User model should have a has_many book_suggestions

2018-11-28 14:42 UTC, lmasello commented
The PR description should be in English too.

2018-11-28 16:45 UTC, lmasello requested changes
Be careful, you are adding .DS_Store files

2018-11-28 16:45 UTC, lmasello commented on app/models/user.rb
> +  has_many :book_suggestion, dependent: :destroy
book_suggestions

2018-11-29 13:21 UTC, lmasello commented
@MaaooVaass Be careful, you are adding .DS_Store files

2018-11-29 16:18 UTC, fedeest approved these changes

2018-11-29 18:40 UTC, lmasello approved these changes

2018-11-30 02:06 UTC, merged