implement open service
wolox-training/dv-rails pull request #21
Opened 2018-12-03 23:06 UTC by MaaooVaass

## Summary
implement open service and create new service folder

## Card
https://trello.com/c/YQlP8f2F/36-integraci%C3%B3n-api-externa

2018-12-04 13:50 UTC, fedeest requested changes

2018-12-04 13:50 UTC, fedeest commented on app/controllers/books_controller.rb
> +    return render json: { error: t('.no_book_error', code: isbn) }, status: :not_found if
Don't do a one line if it doesn't fit in one line.

2018-12-04 13:50 UTC, fedeest commented on app/controllers/books_controller.rb
> +    return render json: { error: t('.no_isbn') }, status: :bad_request if isbn.nil?
Where's this translation added?

2018-12-04 13:50 UTC, fedeest commented on app/controllers/books_controller.rb
> +  end
Add tests for this endpoint

2018-12-04 13:59 UTC, lmasello requested changes

2018-12-04 13:59 UTC, lmasello commented on app/controllers/books_controller.rb
> +    isbn = params[:isbn]
Redundant variable, you can just use the `params[:isbn]`

2018-12-04 13:59 UTC, lmasello commented on app/controllers/books_controller.rb
> +    return render json: { error: t('.no_isbn') }, status: :bad_request if isbn.nil?
Where is this translation defined?

2018-12-04 13:59 UTC, lmasello commented on app/controllers/books_controller.rb
> +    return render json: { error: t('.no_isbn') }, status: :bad_request if isbn.nil?
Also, you can use strong parameters and avoid checking that the parameter is being sent.
Some method similar to this:
```ruby
def book_info_params
  params.require(:isbn)
end
```

2018-12-04 13:59 UTC, lmasello commented on app/controllers/books_controller.rb
> +    return render json: { error: t('.no_book_error', code: isbn) }, status: :not_found if
No need to check whether the external service returns nothing or not.

2018-12-04 13:59 UTC, lmasello commented on app/controllers/books_controller.rb
> +
Empty line :)

2018-12-04 14:09 UTC, lmasello requested changes

2018-12-04 14:09 UTC, lmasello commented on app/services/open_library_service.rb
> +
Empty line

2018-12-04 14:09 UTC, lmasello commented on app/services/open_library_service.rb
> +class OpenLibraryService
We should also test this Service with rspec. For that purposes we need to mock the response of the external API. I recommend that you read the following article: https://8thlight.com/blog/dariusz-pasciak/2016/09/08/better-rspec-stubbing.html

We can make a call after that

2018-12-05 14:41 UTC, lmasello requested changes

2018-12-05 14:41 UTC, lmasello commented on app/controllers/books_controller.rb
> +    params.require(:isbn)
You can create a private method for this param, such as `info_book_params` and then in the OpenLibraryService call, do `OpenLibraryService.new(info_book_params).book_info`

2018-12-05 14:41 UTC, lmasello commented on config/locales/en.yml
> +  book_title: "Book title: %{book_t}"
Avoid unnecessary abbreviations

2018-12-07 13:51 UTC, fedeest requested changes

2018-12-07 13:51 UTC, fedeest commented on spec/services/open_library_spec.rb
> +      }.to_json
Somethings not right here. You are missing the `end` from the `do` block of the `let`

2018-12-07 13:51 UTC, fedeest commented on spec/services/open_library_spec.rb
> +        it 'responds with 404 if the book info do not exist' do
Change this description accordingly

2018-12-07 20:10 UTC, fedeest approved these changes

2018-12-07 20:13 UTC, lmasello approved these changes
Well done! :+1:

2018-12-11 21:58 UTC, merged