Travis
wolox-training/dv-rails pull request #3
Opened 2018-10-30 16:18 UTC by MaaooVaass

functionality with travis

## Trello cards 
https://trello.com/c/tgcJDvVv/13-configurar-travisci

2018-11-01 13:31 UTC, lmasello requested changes

2018-11-01 13:31 UTC, lmasello commented on .travis.yml
> +addons:
No need for this one

2018-11-01 13:31 UTC, lmasello commented on .travis.yml
> +  #- redis-server
We usually remove the line instead of leaving it commented (the same for the others below)

2018-11-01 18:32 UTC, fedeest requested changes
Small change

2018-11-01 18:32 UTC, fedeest commented on .travis.yml
> + # - bundle exec rspec spec -fd
Remove commented line

2018-11-01 18:32 UTC, fedeest commented on Gemfile
> +# frozen_string_literal: true
Didn't you include the configuration for rubocop so that you don't have to do this evey time?

2018-11-01 19:14 UTC, lmasello commented on .travis.yml
> +
What about the removed rvm?

2018-11-01 19:42 UTC, lmasello approved these changes

2018-11-06 18:03 UTC, fedeest approved these changes

2018-11-06 21:00 UTC, merged