Devise
wolox-training/dv-rails pull request #4
Opened 2018-11-01 18:43 UTC by MaaooVaass

## summary
create the migration with devise

## Card trello 
https://trello.com/c/bHvVAx8O/9-instalar-configurar-devise-y-crear-user

2018-11-06 18:05 UTC, lmasello requested changes

2018-11-06 18:05 UTC, lmasello commented on app/models/model.rb
> +class Model < ApplicationRecord
We don't need this model, do we?

2018-11-07 13:28 UTC, fedeest requested changes
Please apply the changes I've marked on the other PR in this one and change base branch of the other PR to this one.

2018-11-07 18:28 UTC, lmasello approved these changes

2018-11-07 18:37 UTC, fedeest approved these changes

2018-11-07 18:38 UTC, merged