Devise token auth
wolox-training/dv-rails pull request #5
Opened 2018-11-06 21:58 UTC by MaaooVaass

## summary
Implement authentication with devise-token-auth.

## Cards 
https://trello.com/c/RU3mYZwO/24-implementar-autenticaci%C3%B3n

2018-11-07 12:14 UTC, fedeest requested changes

2018-11-07 12:14 UTC, fedeest commented on app/models/model.rb
> +end
Erase this, it's an example

2018-11-07 12:14 UTC, fedeest commented on db/migrate/20181101172146_devise_create_users.rb
> +      t.datetime :remember_created_at
Your user is neither recoverable nor rememberable. This fields should not be included

2018-11-07 12:14 UTC, fedeest commented on app/models/user.rb
> +                    #:recoverable, :rememberable, :trackable, :validatable,
I recommend adding trackable as well on real use cases. You can keep it this way if you like.

2018-11-07 12:14 UTC, fedeest commented on db/migrate/20181102224936_devise_token_auth_create_users.rb
> +  end
Why are you adding all these columns here?

2018-11-07 19:00 UTC, lmasello approved these changes
Correct fede's corrections and it's good to go!

2018-11-09 16:01 UTC, fedeest approved these changes

2018-11-09 23:06 UTC, merged