tests for books model
wolox-training/dv-rails pull request #7
Opened 2018-11-09 23:04 UTC by MaaooVaass

## summary
tests for books model
## Cards
https://trello.com/c/z381r4Zx/21-crear-tests-para-el-modelo-de-book

2018-11-12 18:03 UTC, fedeest requested changes

2018-11-12 18:03 UTC, fedeest commented on app/models/book.rb
> +end
Didn't you include this already on some other PR?

2018-11-13 17:34 UTC, lmasello requested changes

2018-11-13 17:34 UTC, lmasello commented on Gemfile
> +gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'master'
It's better to specify the gem version.
Example:
` gem 'faker', '~> 1.9.1' `

2018-11-13 17:34 UTC, lmasello commented on spec/book_spec.rb
> +  it do
We can put each it in just one line :)
` it { should validate_presence_of(:genre) }`

We can also use is_expected.to:
`it { is_expected.to validate_presence_of(:genre) }`

2018-11-13 17:34 UTC, lmasello commented on spec/book_spec.rb
> +  subject(:book) do
It's also better to write subject and lets before the 'it's

2018-11-13 17:36 UTC, lmasello commented on spec/book_spec.rb
> +  it do
https://github.com/thoughtbot/shoulda-matchers#should-vs-is_expectedto

2018-11-14 14:03 UTC, lmasello approved these changes

2018-11-15 13:48 UTC, fedeest approved these changes

2018-11-15 15:20 UTC, merged